title: Bhavishya Velaga # your name (or website title) here
logo: "/pro.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Software Engineer
  <br><br>
  <a href="mailto:aashima.ahuja811@gmail.com">aashima.ahuja811@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/BhavishyaVelaga/">LinkedIn Profile</a>
  <br>
  <a href="https://www.github.com/bhavishyavelaga/">Github</a> 
theme: jekyll-theme-minimal
